# Copyright (c) PRO-Robotech
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v2
name: kaname
version: 0.1.0
appVersion: 0.1.0
description: Kaname (Account, Project, User, ServiceAccount, Group, Role, AccessBinding)
